import { GoogleGenAI } from "@google/genai";

export async function onRequest(context: any) {
    if (context.request.method !== "POST") {
        return new Response("Method Not Allowed", { status: 405 });
    }

    try {
        const ai = new GoogleGenAI({ apiKey: context.env.API_KEY });
        const body = await context.request.json();
        const { type, action } = body;

        // Helper functions inside the worker
        const getStylePrompt = (style: string): string => {
            switch (style) {
                case 'FANTASY_OIL': return "Oil painting style, classical fantasy, highly detailed, dramatic lighting, Magic the Gathering style";
                case 'CYBERPUNK': return "Cyberpunk 2077 style, neon lights, high tech, low life, futuristic, digital art, glitch effects";
                case 'PIXEL_ART': return "16-bit pixel art, retro game style, vibrant colors, clean lines";
                case 'ANIME': return "Anime style, cell shaded, Studio Ghibli inspired, expressive, vibrant";
                case 'LOVECRAFT': return "Eldritch horror style, dark, gloomy, sketching, etching style, mysterious";
                case 'MINIMALIST': return "Vector art, flat design, minimalist, clean, bold shapes, tarot card style";
                default: return "Digital art, high quality";
            }
        };

        // Routing Logic based on 'type' or 'action' payload
        if (type === 'ui_background' || type === 'card_art' || type === 'world_icon' || type === 'board_art') {
            let finalPrompt = "";
            let aspectRatio = "1:1";

            if (type === 'ui_background') {
                finalPrompt = `Abstract wallpaper texture representing ${body.topic}. Style: ${getStylePrompt(body.style)}. Dark, atmospheric, subtle, high contrast, no text, no characters. Suitable for a UI card background.`;
                aspectRatio = "16:9";
            } else if (type === 'card_art') {
                finalPrompt = `${getStylePrompt(body.style)}. Subject: ${body.prompt}. Centered composition, no text, trading card illustration.`;
                aspectRatio = "3:4";
            } else if (type === 'world_icon') {
                finalPrompt = `App icon for a game called "${body.gameName}". Style: ${getStylePrompt(body.style)}. Centered, simple, high contrast, no text. Mobile app icon design.`;
                aspectRatio = "1:1";
            } else if (type === 'board_art') {
                finalPrompt = `Top down view of a card game battle arena (playmat) for a game called "${body.gameName}". Style: ${getStylePrompt(body.style)}. Layout: ${body.boardType}. Material/Texture: ${body.texture}. Primary Accent Color: ${body.primaryColor}. The center should be relatively empty or have faint markings to place cards. The edges should be highly decorated with ${body.style} elements. High contrast, symmetrical, professional game asset, no text.`;
                aspectRatio = "9:16";
            }

            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: { parts: [{ text: finalPrompt }] },
                config: { imageConfig: { aspectRatio } },
            });

            if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
                for (const part of response.candidates[0].content.parts) {
                    if (part.inlineData) {
                        return new Response(JSON.stringify({ image: `data:image/png;base64,${part.inlineData.data}` }), {
                            headers: { 'Content-Type': 'application/json' }
                        });
                    }
                }
            }
            throw new Error("No image generated by AI");
        }

        if (action === 'card_fluff') {
            const response = await ai.models.generateContent({
                model: 'gemini-3-flash-preview',
                contents: `Context: A card game about "${body.gameContext}". Write a 1-sentence flavor text/effect for a ${body.type} card named "${body.name}". make it sound epic.`,
            });
            return new Response(JSON.stringify({ text: response.text }), { headers: { 'Content-Type': 'application/json' } });
        }

        if (action === 'promo_cards') {
            let instructions = `Read these game rules for "${body.gameName}":\n${body.rulesText}\nCreate exactly 3 short "Promo Cards" to teach a new player the vibe and mechanics.`;
            if (body.customSlots && body.customSlots.length === 3) {
                instructions += `\nSTRICTLY FOLLOW these 3 card requests:\n1. Type/Role: ${body.customSlots[0].archetype}. Theme/Content: ${body.customSlots[0].hint || 'AI Choice'}.\n2. Type/Role: ${body.customSlots[1].archetype}. Theme/Content: ${body.customSlots[1].hint || 'AI Choice'}.\n3. Type/Role: ${body.customSlots[2].archetype}. Theme/Content: ${body.customSlots[2].hint || 'AI Choice'}.`;
            } else {
                instructions += `\nMake them diverse (e.g., one Unit, one Spell, one Boss/Finisher).`;
            }
            instructions += `\nReturn JSON format: Array of objects with keys: title (max 3 words), description (max 15 words), icon (a font-awesome class name like 'fa-skull', 'fa-bolt', 'fa-flag').`;

            const response = await ai.models.generateContent({
                model: 'gemini-3-flash-preview',
                contents: instructions,
                config: { responseMimeType: 'application/json' }
            });
            return new Response(JSON.stringify({ text: response.text }), { headers: { 'Content-Type': 'application/json' } });
        }

        if (action === 'rule_assistance') {
            const response = await ai.models.generateContent({
                model: 'gemini-3-pro-preview',
                contents: `Act as a Game Designer. Create a concise, structured rule summary for a card game called "${body.gameName}".\nGame Inputs:\n- Win Condition: ${body.winCondition}\n- Resources: ${body.resourceSystem}\n- Board Type: ${body.boardType}\nOutput Format (Markdown):\n## Objective\n[Explain how to win based on input]\n\n## Setup & Board\n[Explain the ${body.boardType} layout]\n\n## Turn Sequence\n1. Draw\n2. Action\n3. End\n\n## Mechanics\n[Explain resources and combat]`,
            });
            return new Response(JSON.stringify({ text: response.text }), { headers: { 'Content-Type': 'application/json' } });
        }

        return new Response(JSON.stringify({ error: "Invalid action or type" }), { status: 400, headers: { 'Content-Type': 'application/json' } });
    } catch (err: any) {
        console.error(err);
        return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: { 'Content-Type': 'application/json' } });
    }
}
